"""replace_file_name_with_sequence_number_in_income_proof_documents

Revision ID: 01153a8d7962
Revises: 67415d3805a3
Create Date: 2025-06-30 21:58:07.029255

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01153a8d7962'
down_revision = '67415d3805a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('income_proof_documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sequence_number', sa.Integer(), nullable=True))
        batch_op.alter_column('client_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('file_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('income_proof_documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.alter_column('client_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('sequence_number')

    # ### end Alembic commands ###
