"""empty message

Revision ID: 04cfe7fe8be2
Revises: 2e658c5f1e95
Create Date: 2025-02-11 18:51:59.169821

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '04cfe7fe8be2'
down_revision = '2e658c5f1e95'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('banks_offers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('banco_id', sa.Integer(), nullable=False),
    sa.Column('lowest_interest_rate', sa.Float(), nullable=False),
    sa.Column('highest_interest_rate', sa.Float(), nullable=False),
    sa.Column('opening_fee', sa.Float(), nullable=False),
    sa.Column('min_amount_to_finance', sa.Integer(), nullable=False),
    sa.Column('max_amount_to_finance', sa.Integer(), nullable=False),
    sa.Column('income_proof', sa.Boolean(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['banco_id'], ['bancos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=False)

    op.drop_table('banks_offers')
    # ### end Alembic commands ###
