"""Add columns for user for set clock selection meththod

Revision ID: 04e22aa18650
Revises: af21dcf7f667
Create Date: 2025-04-03 03:41:52.786321

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04e22aa18650'
down_revision = 'af21dcf7f667'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_selected', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('last_selected_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('last_selected_at')
        batch_op.drop_column('is_selected')

    # ### end Alembic commands ###
