"""add preferred_store column to solicitudes modelel

Revision ID: 05d8a75411fa
Revises: f193e17c3123
Create Date: 2025-04-07 18:19:56.011649

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05d8a75411fa'
down_revision = 'f193e17c3123'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('solicitudes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('preferred_store', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('solicitudes', schema=None) as batch_op:
        batch_op.drop_column('preferred_store')

    # ### end Alembic commands ###
