"""Add columns status_code and status_message

Revision ID: 0676acc91191
Revises: 1a426f4e7d6f
Create Date: 2025-07-11 10:33:10.539806

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0676acc91191'
down_revision = '1a426f4e7d6f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status_code', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('status_message', sa.Text(), nullable=True))
        batch_op.drop_constraint('messages_conversation_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'conversations', ['conversation_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('messages_conversation_id_fkey', 'conversations', ['conversation_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
        batch_op.drop_column('status_message')
        batch_op.drop_column('status_code')

    # ### end Alembic commands ###
