"""Set nullable values for client model

Revision ID: 0753c5c13198
Revises: 69334d51f9c4
Create Date: 2025-04-23 13:45:56.248957

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0753c5c13198'
down_revision = '69334d51f9c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.alter_column('first_last_name',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('second_last_name',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('birth_date',
               existing_type=sa.DATE(),
               nullable=True)
        batch_op.alter_column('sex',
               existing_type=sa.VARCHAR(length=1),
               nullable=True)
        batch_op.alter_column('rfc',
               existing_type=sa.VARCHAR(length=13),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.alter_column('rfc',
               existing_type=sa.VARCHAR(length=13),
               nullable=False)
        batch_op.alter_column('sex',
               existing_type=sa.VARCHAR(length=1),
               nullable=False)
        batch_op.alter_column('birth_date',
               existing_type=sa.DATE(),
               nullable=False)
        batch_op.alter_column('second_last_name',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('first_last_name',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)

    # ### end Alembic commands ###
