"""empty message

Revision ID: 09518b684787
Revises: 4f8f96162206
Create Date: 2025-06-09 08:23:18.357698

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09518b684787'
down_revision = '4f8f96162206'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('file_statuses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('incomeProof_two', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('incomeProof_three', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('file_statuses', schema=None) as batch_op:
        batch_op.drop_column('incomeProof_three')
        batch_op.drop_column('incomeProof_two')

    # ### end Alembic commands ###
