"""add cascade for clientes_users and solicitud_bananks association tables

Revision ID: 0b73e378b4c3
Revises: a735f440eb66
Create Date: 2025-05-06 10:07:18.062775

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b73e378b4c3'
down_revision = 'a735f440eb66'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clientes_users', schema=None) as batch_op:
        batch_op.drop_constraint('clientes_users_user_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('clientes_users_cliente_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'clientes', ['cliente_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('solicitud_banks', schema=None) as batch_op:
        batch_op.drop_constraint('solicitud_banks_bank_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('solicitud_banks_solicitud_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'bancos', ['bank_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'solicitudes', ['solicitud_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('solicitud_banks', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('solicitud_banks_solicitud_id_fkey', 'solicitudes', ['solicitud_id'], ['id'])
        batch_op.create_foreign_key('solicitud_banks_bank_id_fkey', 'bancos', ['bank_id'], ['id'])

    with op.batch_alter_table('clientes_users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('clientes_users_cliente_id_fkey', 'clientes', ['cliente_id'], ['id'])
        batch_op.create_foreign_key('clientes_users_user_id_fkey', 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###
