"""empty message

Revision ID: 0e33f11f8b4a
Revises: d28cb59ac267
Create Date: 2025-08-13 01:11:48.348862

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e33f11f8b4a'
down_revision = 'd28cb59ac267'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('whatsapp_id_numbers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('whatsapp_id_number', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('api_key', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('whatsapp_number_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('conversations_assigned_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'whatsapp_id_numbers', ['whatsapp_number_id'], ['id'])
        batch_op.drop_column('assigned_user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assigned_user_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('conversations_assigned_user_id_fkey', 'users', ['assigned_user_id'], ['id'])
        batch_op.drop_column('whatsapp_number_id')

    op.drop_table('whatsapp_id_numbers')
    # ### end Alembic commands ###
