"""Add inner_brand_model column to motorcycles

Revision ID: 177da8cb810e
Revises: 84d9d8122d78
Create Date: 2025-09-15 12:06:06.054174

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '177da8cb810e'
down_revision = '84d9d8122d78'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('motorcycles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('inner_brand_model', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('motorcycles', schema=None) as batch_op:
        batch_op.drop_column('inner_brand_model')

    # ### end Alembic commands ###
