"""Add cascade delete for relation between converstaion and messages model, also add unique case for phone column of conversation model

Revision ID: 1a426f4e7d6f
Revises: 66e2b7d43b7c
Create Date: 2025-07-09 13:19:14.065444

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a426f4e7d6f'
down_revision = '66e2b7d43b7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['phone_number'])

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_constraint('messages_conversation_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'conversations', ['conversation_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('messages_conversation_id_fkey', 'conversations', ['conversation_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')

    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
