"""Set BankZoneLimit

Revision ID: 1abfa6fe61e4
Revises: df95366379a4
Create Date: 2025-09-08 14:03:51.215578

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1abfa6fe61e4'
down_revision = 'df95366379a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bank_zone_limits',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('bank_id', sa.Integer(), nullable=False),
    sa.Column('limit_type', sa.Enum('STATE', 'MUNICIPALITY', 'ZIP_CODE', 'NEIGHBORHOOD', name='limittype'), nullable=False),
    sa.Column('limit_value', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['bank_id'], ['bancos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bank_zone_limits')
    # ### end Alembic commands ###
