"""LA-400 - Set motorcycle_id column in ClientesUnknown model

Revision ID: 24a0d7da2423
Revises: d8f9c03b0650
Create Date: 2025-09-02 00:52:04.117872

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24a0d7da2423'
down_revision = 'd8f9c03b0650'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('banks_offers_requirements', schema=None) as batch_op:
        batch_op.drop_index('ix_banks_offers_requirements_bank_id')
        batch_op.drop_index('ix_banks_offers_requirements_field_reference')
        batch_op.drop_index('ix_banks_offers_requirements_requirement_status')

    with op.batch_alter_table('clientes_unknown', schema=None) as batch_op:
        batch_op.add_column(sa.Column('motorcycle_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'motorcycles', ['motorcycle_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.alter_column('ticket',
               existing_type=sa.VARCHAR(length=13),
               type_=sa.String(length=15),
               existing_nullable=True)
        batch_op.drop_column('mercado_pago_fee')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mercado_pago_fee', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.alter_column('ticket',
               existing_type=sa.String(length=15),
               type_=sa.VARCHAR(length=13),
               existing_nullable=True)

    with op.batch_alter_table('clientes_unknown', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('motorcycle_id')

    with op.batch_alter_table('banks_offers_requirements', schema=None) as batch_op:
        batch_op.create_index('ix_banks_offers_requirements_requirement_status', ['requirement_status'], unique=False)
        batch_op.create_index('ix_banks_offers_requirements_field_reference', ['field_reference'], unique=False)
        batch_op.create_index('ix_banks_offers_requirements_bank_id', ['bank_id'], unique=False)

    # ### end Alembic commands ###
