"""create brands model

Revision ID: 266c57523eae
Revises: 04e22aa18650
Create Date: 2025-04-03 12:40:41.016230

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "266c57523eae"
down_revision = "04e22aa18650"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "motorcycle_brands",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    with op.batch_alter_table("banks_offers", schema=None) as batch_op:
        batch_op.add_column(sa.Column("brand_id", sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, "motorcycle_brands", ["brand_id"], ["id"])

    with op.batch_alter_table("motorcycles", schema=None) as batch_op:
        batch_op.add_column(sa.Column("brand_id", sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, "motorcycle_brands", ["brand_id"], ["id"])

    with op.batch_alter_table("sucursales", schema=None) as batch_op:
        batch_op.add_column(sa.Column("brand_id", sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, "motorcycle_brands", ["brand_id"], ["id"])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("sucursales", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.drop_column("brand_id")

    with op.batch_alter_table("motorcycles", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.drop_column("brand_id")

    with op.batch_alter_table("banks_offers", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.drop_column("brand_id")

    op.drop_table("motorcycle_brands")
    # ### end Alembic commands ###
