"""Set table for save the whatsapp templates content

Revision ID: 2db04f919bf2
Revises: 3cecb4906d99
Create Date: 2025-09-30 13:26:43.392814

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2db04f919bf2'
down_revision = '3cecb4906d99'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('whatsapp_template_messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('whatsapp_template_messages')
    # ### end Alembic commands ###
