"""add zip_code column for sucursal model LA-126

Revision ID: 2e658c5f1e95
Revises: 50af1df45590
Create Date: 2025-02-06 00:15:03.635588

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e658c5f1e95'
down_revision = '50af1df45590'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sucursales', schema=None) as batch_op:
        batch_op.add_column(sa.Column('zip_code', sa.String(length=5), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sucursales', schema=None) as batch_op:
        batch_op.drop_column('zip_code')

    # ### end Alembic commands ###
