"""New credit_preference column

Revision ID: 2fce93cc1eb7
Revises: 39e51f13a265
Create Date: 2025-10-14 13:25:57.062148

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2fce93cc1eb7'
down_revision = '39e51f13a265'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('solicitudes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('credit_preference', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('solicitudes', schema=None) as batch_op:
        batch_op.drop_column('credit_preference')

    # ### end Alembic commands ###
