"""empty message

Revision ID: 30ba280d5792
Revises: 81a501e85acb
Create Date: 2025-04-04 15:55:31.439596

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30ba280d5792'
down_revision = '81a501e85acb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('banks_offers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('brand_id', sa.Integer(), nullable=True))
        batch_op.alter_column('min_downpayment',
               existing_type=sa.REAL(),
               type_=sa.Integer(),
               nullable=False)
        batch_op.alter_column('max_downpayment',
               existing_type=sa.REAL(),
               type_=sa.Integer(),
               nullable=False)
        batch_op.alter_column('min_loan_term_months',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('max_loan_term_months',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.create_foreign_key(None, 'motorcycle_brands', ['brand_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('banks_offers', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('max_loan_term_months',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('min_loan_term_months',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('max_downpayment',
               existing_type=sa.Integer(),
               type_=sa.REAL(),
               nullable=True)
        batch_op.alter_column('min_downpayment',
               existing_type=sa.Integer(),
               type_=sa.REAL(),
               nullable=True)
        batch_op.drop_column('brand_id')

    # ### end Alembic commands ###
