"""Add motorcycle_existance and motorcycle_existance_updated_at to motorcycles table

Revision ID: 3740b066111a
Revises: 413cce0e490c
Create Date: 2025-06-11 23:15:04.748981

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3740b066111a'
down_revision = '413cce0e490c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('motorcycles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('motorcycle_existance', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('motorcycle_existance_updated_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('motorcycles', schema=None) as batch_op:
        batch_op.drop_column('motorcycle_existance_updated_at')
        batch_op.drop_column('motorcycle_existance')

    # ### end Alembic commands ###
