"""Add utm columns to solicitud model

Revision ID: 39e51f13a265
Revises: 4231d26dfd11
Create Date: 2025-10-04 02:09:19.594110

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39e51f13a265'
down_revision = '4231d26dfd11'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('solicitudes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('utm_source', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('utm_medium', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('utm_campaign', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('utm_content', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('utm_term', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('other_url_params', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('solicitudes', schema=None) as batch_op:
        batch_op.drop_column('other_url_params')
        batch_op.drop_column('utm_term')
        batch_op.drop_column('utm_content')
        batch_op.drop_column('utm_campaign')
        batch_op.drop_column('utm_medium')
        batch_op.drop_column('utm_source')

    # ### end Alembic commands ###
