"""create interest type columns

Revision ID: 3cecb4906d99
Revises: f37da03d1d05
Create Date: 2025-09-25 18:10:11.074341

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3cecb4906d99'
down_revision = 'f37da03d1d05'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # Create the enum type first
    interesttype_enum = sa.Enum('AVG_INTEREST', 'INTEREST_PER_TERM', name='interesttype')
    interesttype_enum.create(op.get_bind())

    with op.batch_alter_table('banks_offers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('interest_type', interesttype_enum, nullable=True))
        batch_op.add_column(sa.Column('interest_term', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('banks_offers', schema=None) as batch_op:
        batch_op.drop_column('interest_term')
        batch_op.drop_column('interest_type')

    # ### end Alembic commands ###
