"""add changes for payments model

Revision ID: 407648fadc01
Revises: 4625e56eb805
Create Date: 2025-04-11 19:49:39.316746

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '407648fadc01'
down_revision = '4625e56eb805'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('banks_offers', schema=None) as batch_op:
        batch_op.alter_column('min_invoice_value',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('max_invoice_value',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('min_downpayment',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=False)
        batch_op.alter_column('max_downpayment',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=False)

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('net_received_amount', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('financing_fee', sa.Float(), nullable=True))
        batch_op.alter_column('commission',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
        batch_op.alter_column('operation_number_mercadopago',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('installments',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('installment_amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
        batch_op.alter_column('amount_charged_cc',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
        batch_op.alter_column('mercado_pago_fee',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
        batch_op.drop_column('received_by_dealer')
        batch_op.drop_column('finva_fee')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('finva_fee', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('received_by_dealer', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
        batch_op.alter_column('mercado_pago_fee',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
        batch_op.alter_column('amount_charged_cc',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
        batch_op.alter_column('installment_amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
        batch_op.alter_column('installments',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('operation_number_mercadopago',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('commission',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
        batch_op.drop_column('financing_fee')
        batch_op.drop_column('net_received_amount')

    with op.batch_alter_table('banks_offers', schema=None) as batch_op:
        batch_op.alter_column('max_downpayment',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=False)
        batch_op.alter_column('min_downpayment',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=False)
        batch_op.alter_column('max_invoice_value',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('min_invoice_value',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
