"""Add ai_assisted column to solicitud

Revision ID: 419c7c8d4b77
Revises: 2fce93cc1eb7
Create Date: 2025-10-20 16:31:12.474061

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '419c7c8d4b77'
down_revision = '2fce93cc1eb7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.drop_constraint('conversations_whatsapp_number_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'whatsapp_id_numbers', ['whatsapp_number_id'], ['id'])

    with op.batch_alter_table('solicitudes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ai_assisted', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('solicitudes', schema=None) as batch_op:
        batch_op.drop_column('ai_assisted')

    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('conversations_whatsapp_number_id_fkey', 'whatsapp_id_numbers', ['whatsapp_number_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')

    # ### end Alembic commands ###
