"""add_conditional_requirement_group_column

Revision ID: 4231d26dfd11
Revises: 0a822b5c5932
Create Date: 2025-10-02 23:58:59.189359

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4231d26dfd11'
down_revision = '0a822b5c5932'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('banks_offers_requirements', schema=None) as batch_op:
        batch_op.add_column(sa.Column('conditional_requirement_group', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('banks_offers_requirements', schema=None) as batch_op:
        batch_op.drop_column('conditional_requirement_group')

    # ### end Alembic commands ###
