"""change names of columns for financingOption model

Revision ID: 4625e56eb805
Revises: 05d8a75411fa
Create Date: 2025-04-09 00:58:18.796044

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4625e56eb805'
down_revision = '05d8a75411fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('banks_offers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('min_invoice_value', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('max_invoice_value', sa.Integer(), nullable=True))
        batch_op.alter_column('min_downpayment',
               existing_type=sa.REAL(),
               type_=sa.Integer(),
               existing_nullable=False)
        batch_op.alter_column('max_downpayment',
               existing_type=sa.REAL(),
               type_=sa.Integer(),
               existing_nullable=False)
        batch_op.drop_column('min_amount_to_finance')
        batch_op.drop_column('max_amount_to_finance')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('banks_offers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('max_amount_to_finance', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('min_amount_to_finance', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.alter_column('max_downpayment',
               existing_type=sa.Integer(),
               type_=sa.REAL(),
               existing_nullable=False)
        batch_op.alter_column('min_downpayment',
               existing_type=sa.Integer(),
               type_=sa.REAL(),
               existing_nullable=False)
        batch_op.drop_column('max_invoice_value')
        batch_op.drop_column('min_invoice_value')

    # ### end Alembic commands ###
