"""Add holding_page_url column to solicitudes and unknown-clients

Revision ID: 47f1314cef9c
Revises: 08bde2691991
Create Date: 2025-11-07 11:46:20.432290

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47f1314cef9c'
down_revision = '08bde2691991'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clientes_unknown', schema=None) as batch_op:
        batch_op.add_column(sa.Column('holding_page_url', sa.String(), nullable=True))

    with op.batch_alter_table('solicitudes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('holding_page_url', sa.String(), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))

    with op.batch_alter_table('solicitudes', schema=None) as batch_op:
        batch_op.drop_column('holding_page_url')

    with op.batch_alter_table('clientes_unknown', schema=None) as batch_op:
        batch_op.drop_column('holding_page_url')

    # ### end Alembic commands ###
