"""Add column for set finva_user_id

Revision ID: 4f8f96162206
Revises: 5ec6d658d635
Create Date: 2025-06-04 23:33:20.817918

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f8f96162206'
down_revision = '5ec6d658d635'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('solicitudes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('finva_user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['finva_user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('solicitudes', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('finva_user_id')

    # ### end Alembic commands ###
