"""add cascade delete to relationship between payment and purchase

Revision ID: 50af1df45590
Revises: 412ef2b3e72f
Create Date: 2025-02-05 23:28:51.651133

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50af1df45590'
down_revision = '412ef2b3e72f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_constraint('payments_purchase_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'purchases', ['purchase_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('payments_purchase_id_fkey', 'purchases', ['purchase_id'], ['id'])

    # ### end Alembic commands ###
