"""empty message

Revision ID: 569ac5a8bbde
Revises: 07dc74d20852
Create Date: 2025-08-12 14:35:52.452948

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '569ac5a8bbde'
down_revision = '07dc74d20852'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reply_to_message_id', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_column('reply_to_message_id')

    # ### end Alembic commands ###
