"""Delete media_url and media_caption columns and d set media_id column instead

Revision ID: 66e2b7d43b7c
Revises: 9ce9eb815663
Create Date: 2025-07-07 14:48:12.471502

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66e2b7d43b7c'
down_revision = '9ce9eb815663'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('media_id', sa.String(length=100), nullable=True))
        batch_op.drop_column('media_url')
        batch_op.drop_column('media_caption')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('media_caption', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('media_url', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.drop_column('media_id')

    # ### end Alembic commands ###
