"""Add total income column to incomeproof model

Revision ID: 67415d3805a3
Revises: dc6f0e9c4661
Create Date: 2025-06-30 15:54:09.069235

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = '67415d3805a3'
down_revision = 'dc6f0e9c4661'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('income_proof_documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_income', sa.Float(), nullable=True))
        batch_op.alter_column('month',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Integer(),
               postgresql_using="month::integer",
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('income_proof_documents', schema=None) as batch_op:
        batch_op.alter_column('month',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=20),
               postgresql_using="month::varchar",
               existing_nullable=True)
        batch_op.drop_column('total_income')

    # ### end Alembic commands ###
