"""LA-236 - Add ContactAttempt and SolicitudUserOwners models

Revision ID: 68e1ec95cb9a
Revises: ccd333b5ce6f
Create Date: 2025-07-24 14:37:40.413730

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68e1ec95cb9a'
down_revision = 'ccd333b5ce6f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('solicitud_user_owners',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('solicitud_id', sa.Integer(), nullable=False),
    sa.Column('user_type_reassigned', sa.String(length=20), nullable=False),
    sa.Column('old_user_id', sa.Integer(), nullable=True),
    sa.Column('new_user_id', sa.Integer(), nullable=True),
    sa.Column('reassigned_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['new_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['old_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reassigned_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['solicitud_id'], ['solicitudes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contact_attempts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('solicitud_status_history_id', sa.Integer(), nullable=False),
    sa.Column('no_contact_attempt', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['solicitud_status_history_id'], ['solicitud_status_history.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reminders', schema=None) as batch_op:
        batch_op.drop_index('ix_reminders_reminder_datetime')
        batch_op.drop_index('ix_reminders_status')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reminders', schema=None) as batch_op:
        batch_op.create_index('ix_reminders_status', ['status'], unique=False)
        batch_op.create_index('ix_reminders_reminder_datetime', ['reminder_datetime'], unique=False)

    op.drop_table('contact_attempts')
    op.drop_table('solicitud_user_owners')
    # ### end Alembic commands ###
