"""empty message

Revision ID: 69334d51f9c4
Revises: 407648fadc01
Create Date: 2025-04-22 13:10:38.774437

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69334d51f9c4'
down_revision = '407648fadc01'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('solicitudes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('time_to_buy_motorcycle', sa.String(), nullable=True))

    with op.batch_alter_table('user_sucursales', schema=None) as batch_op:
        batch_op.drop_constraint('user_sucursales_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_sucursales', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('user_sucursales_user_id_fkey', 'users', ['user_id'], ['id'], onupdate='RESTRICT', ondelete='CASCADE')

    with op.batch_alter_table('solicitudes', schema=None) as batch_op:
        batch_op.drop_column('time_to_buy_motorcycle')

    # ### end Alembic commands ###
