"""Add cascade delete to relation between conversation and client

Revision ID: 7451da5f42f6
Revises: 9891669c2cb9
Create Date: 2025-07-18 00:27:33.990234

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7451da5f42f6'
down_revision = '9891669c2cb9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.drop_constraint('conversations_client_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'clientes', ['client_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('conversations_client_id_fkey', 'clientes', ['client_id'], ['id'])

    # ### end Alembic commands ###
