"""Add bank_offer_id to BankOfferRequirement and remove bank_id

Revision ID: 74be7c8ad79a
Revises: ca88ebe1db16
Create Date: 2025-09-04 10:04:04.099485

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74be7c8ad79a'
down_revision = 'ca88ebe1db16'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('banks_offers_requirements', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bank_offer_id', sa.Integer(), nullable=False))
        batch_op.alter_column('requirement_key',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.drop_constraint('banks_offers_requirements_bank_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'banks_offers', ['bank_offer_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('bank_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('banks_offers_requirements', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bank_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('banks_offers_requirements_bank_id_fkey', 'bancos', ['bank_id'], ['id'], ondelete='CASCADE')
        batch_op.alter_column('requirement_key',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.drop_column('bank_offer_id')

    # ### end Alembic commands ###
