"""Add relation between preferred_store_id scolumn oof solicitud model with sucursales.id

Revision ID: 7e53eb41b7ae
Revises: 0b73e378b4c3
Create Date: 2025-05-09 00:51:48.494503

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e53eb41b7ae'
down_revision = '0b73e378b4c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('solicitudes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('preferred_store_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'sucursales', ['preferred_store_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('solicitudes', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('preferred_store_id')

    # ### end Alembic commands ###
