"""add expiration date for id

Revision ID: 7f372f689034
Revises: 04cfe7fe8be2
Create Date: 2025-02-19 15:01:26.784237

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f372f689034'
down_revision = '04cfe7fe8be2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_expiration_date', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.drop_column('id_expiration_date')

    # ### end Alembic commands ###
