"""delete brand name columns for models with a relation to brands model. and add columns of dowpayment and loan term months to bank_offers

Revision ID: 81a501e85acb
Revises: 266c57523eae
Create Date: 2025-04-03 16:17:51.913696

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81a501e85acb'
down_revision = '266c57523eae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('banks_offers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('min_downpayment', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('max_downpayment', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('min_loan_term_months', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('max_loan_term_months', sa.Integer(), nullable=True))

    with op.batch_alter_table('motorcycles', schema=None) as batch_op:
        batch_op.alter_column('brand_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('brand')

    with op.batch_alter_table('sucursales', schema=None) as batch_op:
        batch_op.alter_column('brand_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('marca')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sucursales', schema=None) as batch_op:
        batch_op.add_column(sa.Column('marca', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.alter_column('brand_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('motorcycles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('brand', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.alter_column('brand_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('banks_offers', schema=None) as batch_op:
        batch_op.drop_column('max_loan_term_months')
        batch_op.drop_column('min_loan_term_months')
        batch_op.drop_column('max_downpayment')
        batch_op.drop_column('min_downpayment')

    # ### end Alembic commands ###
