"""add motorcycle_qualitas_amis table

Revision ID: 81e0394da9fd
Revises: 9c684865f902
Create Date: 2025-06-03 17:06:05.284990

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81e0394da9fd'
down_revision = '9c684865f902'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('claves_amis',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('motorcycle_id', sa.Integer(), nullable=False),
    sa.Column('clave_amis_qualitas', sa.String(length=5), nullable=False),
    sa.ForeignKeyConstraint(['motorcycle_id'], ['motorcycles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('claves_amis')
    # ### end Alembic commands ###
