"""Add bank_offer_name column to banks_offers table

Revision ID: 84d9d8122d78
Revises: 1abfa6fe61e4
Create Date: 2025-09-09 19:11:54.089444

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84d9d8122d78'
down_revision = '1abfa6fe61e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Add column as nullable (matching the model definition)
    with op.batch_alter_table('banks_offers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bank_offer_name', sa.String(), nullable=True))
    
    # Optionally: Update existing records with default values
    # op.execute("UPDATE banks_offers SET bank_offer_name = 'Bank Offer ' || id::text WHERE bank_offer_name IS NULL")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('banks_offers', schema=None) as batch_op:
        batch_op.drop_column('bank_offer_name')
    # ### end Alembic commands ###
