"""LA-520 - Set table for logs

Revision ID: 88f97d3c06b9
Revises: 6d6e349d8cca
Create Date: 2025-11-13 15:34:24.231470

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88f97d3c06b9'
down_revision = '6d6e349d8cca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('log', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_logs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_logs_type'), ['type'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_logs_type'))
        batch_op.drop_index(batch_op.f('ix_logs_created_at'))

    op.drop_table('logs')
    # ### end Alembic commands ###
