"""Add task fields to solicitudes table

Revision ID: 8b306290f287
Revises: b3faece16214
Create Date: 2025-06-20 06:09:00.363718

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b306290f287'
down_revision = 'b3faece16214'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('solicitudes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('task_verify_documents', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('task_check_application_data', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('task_verify_signature', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('task_income_source', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('task_activity_matches_income', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('task_all_income_verified', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('solicitudes', schema=None) as batch_op:
        batch_op.drop_column('task_all_income_verified')
        batch_op.drop_column('task_activity_matches_income')
        batch_op.drop_column('task_income_source')
        batch_op.drop_column('task_verify_signature')
        batch_op.drop_column('task_check_application_data')
        batch_op.drop_column('task_verify_documents')

    # ### end Alembic commands ###
