"""Add association table for FinancingOption (banks_offers) ↔ Motorcycles

Revision ID: 8e663a8d189f
Revises: 0753c5c13198
Create Date: 2025-04-24 10:39:18.675426

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e663a8d189f'
down_revision = '0753c5c13198'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bank_offers_motorcycles',
    sa.Column('bank_offer_id', sa.Integer(), nullable=False),
    sa.Column('motorcycle_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['bank_offer_id'], ['banks_offers.id'], ),
    sa.ForeignKeyConstraint(['motorcycle_id'], ['motorcycles.id'], ),
    sa.PrimaryKeyConstraint('bank_offer_id', 'motorcycle_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bank_offers_motorcycles')
    # ### end Alembic commands ###
