"""Add coordinates column to sucursal model

Revision ID: 9568360abe7a
Revises: 2f56c4d3dcab
Create Date: 2025-11-18 18:32:09.830736

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9568360abe7a'
down_revision = '2f56c4d3dcab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # with op.batch_alter_table('conversations', schema=None) as batch_op:
    #     batch_op.create_unique_constraint(None, ['phone_number'])
    #     batch_op.drop_constraint('conversations_whatsapp_number_id_fkey', type_='foreignkey')
    #     batch_op.create_foreign_key(None, 'whatsapp_id_numbers', ['whatsapp_number_id'], ['id'])

    # with op.batch_alter_table('messages', schema=None) as batch_op:
    #     batch_op.drop_constraint('messages_wa_message_id_key', type_='unique')

    with op.batch_alter_table('sucursales', schema=None) as batch_op:
        batch_op.add_column(sa.Column('coordinates', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sucursales', schema=None) as batch_op:
        batch_op.drop_column('coordinates')

    # with op.batch_alter_table('messages', schema=None) as batch_op:
    #     batch_op.create_unique_constraint('messages_wa_message_id_key', ['wa_message_id'])

    # with op.batch_alter_table('conversations', schema=None) as batch_op:
    #     batch_op.drop_constraint(None, type_='foreignkey')
    #     batch_op.create_foreign_key('conversations_whatsapp_number_id_fkey', 'whatsapp_id_numbers', ['whatsapp_number_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    #     batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
