"""Add media storage fields to Message model

Revision ID: 9891669c2cb9
Revises: b3f0a49242bc
Create Date: 2025-07-11 23:58:38.428631

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9891669c2cb9'
down_revision = 'b3f0a49242bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('media_storage_path', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('media_filename', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('media_mime_type', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('media_file_size', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('media_sha256', sa.String(length=64), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_column('media_sha256')
        batch_op.drop_column('media_file_size')
        batch_op.drop_column('media_mime_type')
        batch_op.drop_column('media_filename')
        batch_op.drop_column('media_storage_path')

    # ### end Alembic commands ###
