"""Add models for message and conversations for whatsapp api

Revision ID: 9ce9eb815663
Revises: 123456789abc
Create Date: 2025-07-04 17:07:11.333623

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "9ce9eb815663"
down_revision = "123456789abc"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "conversations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("wa_thread_id", sa.String(length=100), nullable=True),
        sa.Column("client_id", sa.Integer(), nullable=True),
        sa.Column("assigned_user_id", sa.Integer(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "OPEN", "CLOSED", "PENDING", "NEEDS_REPLY", name="conversationstatus"
            ),
            nullable=True,
        ),
        sa.Column("phone_number", sa.String(length=20), nullable=False),
        sa.Column("last_message_at", sa.DateTime(), nullable=True),
        sa.Column("last_read_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["assigned_user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["client_id"],
            ["clientes.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("wa_thread_id"),
    )
    op.create_table(
        "messages",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("conversation_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("wa_message_id", sa.String(length=100), nullable=False),
        sa.Column(
            "direction",
            sa.Enum("INBOUND", "OUTBOUND", name="messagedirection"),
            nullable=False,
        ),
        sa.Column(
            "message_type",
            sa.Enum(
                "TEXT",
                "IMAGE",
                "VIDEO",
                "AUDIO",
                "DOCUMENT",
                "STICKER",
                "LOCATION",
                "CONTACT",
                "INTERACTIVE",
                name="messagetype",
            ),
            nullable=False,
        ),
        sa.Column("content", sa.Text(), nullable=True),
        sa.Column("media_url", sa.String(length=255), nullable=True),
        sa.Column("media_caption", sa.Text(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "SENT", "DELIVERED", "READ", "FAILED", "RECEIVED", name="messagestatus"
            ),
            nullable=True,
        ),
        sa.Column("timestamp", sa.DateTime(), nullable=False),
        sa.Column("status_updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["conversation_id"],
            ["conversations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("messages")
    op.drop_table("conversations")
    # ### end Alembic commands ###
