"""LA-296 Add column registration_process to Solicitud model

Revision ID: 9db8f13f09c9
Revises: 8b306290f287
Create Date: 2025-06-24 01:34:44.724480

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9db8f13f09c9'
down_revision = '8b306290f287'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('solicitudes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('registration_process', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('solicitudes', schema=None) as batch_op:
        batch_op.drop_column('registration_process')

    # ### end Alembic commands ###
