"""Addd  association table for Solicitud and Banks

Revision ID: a735f440eb66
Revises: d5e2b7c6a33d
Create Date: 2025-05-05 23:33:42.017082

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a735f440eb66'
down_revision = 'd5e2b7c6a33d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('solicitud_banks',
    sa.Column('solicitud_id', sa.Integer(), nullable=False),
    sa.Column('bank_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['bank_id'], ['bancos.id'], ),
    sa.ForeignKeyConstraint(['solicitud_id'], ['solicitudes.id'], ),
    sa.PrimaryKeyConstraint('solicitud_id', 'bank_id')
    )
    with op.batch_alter_table('solicitudes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bank_id_applicated', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'bancos', ['bank_id_applicated'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('solicitudes', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('bank_id_applicated')

    op.drop_table('solicitud_banks')
    # ### end Alembic commands ###
