"""add payment_method column to Solicitudes model

Revision ID: af21dcf7f667
Revises: 08907a9b367f
Create Date: 2025-03-05 00:49:14.227876

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af21dcf7f667'
down_revision = '08907a9b367f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('solicitudes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_method', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('solicitudes', schema=None) as batch_op:
        batch_op.drop_column('payment_method')

    # ### end Alembic commands ###
