"""New column registration_mode

Revision ID: af31d06d625a
Revises: 419c7c8d4b77
Create Date: 2025-10-21 14:56:18.259363

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af31d06d625a'
down_revision = '419c7c8d4b77'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('solicitudes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('registration_mode', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('solicitudes', schema=None) as batch_op:
        batch_op.drop_column('registration_mode')

    # ### end Alembic commands ###
