"""Add id_bank_application column to Application model

Revision ID: b3faece16214
Revises: c8c13c59454f
Create Date: 2025-06-17 05:47:20.678945

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3faece16214'
down_revision = 'c8c13c59454f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_bank_application', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.drop_column('id_bank_application')

    # ### end Alembic commands ###
