"""empty message

Revision ID: bf3507cbf181
Revises: e798088f78fc
Create Date: 2025-02-01 00:46:15.232693

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf3507cbf181'
down_revision = 'e798088f78fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('solicitudes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('friend_reference_zip_code', sa.String(), nullable=True))
        batch_op.drop_column('friend_reference_job_zip_code')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('solicitudes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('friend_reference_job_zip_code', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.drop_column('friend_reference_zip_code')

    # ### end Alembic commands ###
