"""empty message

Revision ID: c30e90a83b98
Revises: b57d278caec5
Create Date: 2025-01-17 14:35:35.687142

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c30e90a83b98'
down_revision = 'b57d278caec5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('finva_evaluation', sa.JSON(), nullable=True))

    with op.batch_alter_table('solicitudes', schema=None) as batch_op:
        batch_op.drop_column('finva_evaluation')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('solicitudes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('finva_evaluation', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))

    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.drop_column('finva_evaluation')

    # ### end Alembic commands ###
