"""LA-380- Add columns for register bank transfers into payments model and set solicitud relation

Revision ID: c7f8b92a9549
Revises: fcfe1bd43cd6
Create Date: 2025-08-27 18:01:56.851398

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7f8b92a9549'
down_revision = 'fcfe1bd43cd6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('solicitud_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('bank_origin_account_number', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('bank_destination_account_number', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('bank_transfer_date', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('bank_transfer_amount', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('ticket', sa.String(length=13), nullable=True))
        batch_op.alter_column('purchase_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('amount_to_finance',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
        batch_op.alter_column('amount_instant_pay',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
        batch_op.alter_column('payment_type',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('cardholder_names',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('cardholder_first_lastname',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.create_unique_constraint(None, ['ticket'])
        batch_op.create_foreign_key(None, 'solicitudes', ['solicitud_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('solicitudes', schema=None) as batch_op:
        batch_op.alter_column('payment_method',
               existing_type=sa.VARCHAR(),
               nullable=False)

    with op.batch_alter_table('sucursales', schema=None) as batch_op:
        batch_op.alter_column('active',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sucursales', schema=None) as batch_op:
        batch_op.alter_column('active',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    with op.batch_alter_table('solicitudes', schema=None) as batch_op:
        batch_op.alter_column('payment_method',
               existing_type=sa.VARCHAR(),
               nullable=True)

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('cardholder_first_lastname',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('cardholder_names',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('payment_type',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('amount_instant_pay',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
        batch_op.alter_column('amount_to_finance',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
        batch_op.alter_column('purchase_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('ticket')
        batch_op.drop_column('bank_transfer_amount')
        batch_op.drop_column('bank_transfer_date')
        batch_op.drop_column('bank_destination_account_number')
        batch_op.drop_column('bank_origin_account_number')
        batch_op.drop_column('solicitud_id')

    # ### end Alembic commands ###
