"""Delete columns of motorcycle model and add it to solicitudes

Revision ID: c8c13c59454f
Revises: 3740b066111a
Create Date: 2025-06-13 00:06:02.332477

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c8c13c59454f'
down_revision = '3740b066111a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('motorcycles', schema=None) as batch_op:
        batch_op.drop_column('motorcycle_existance')
        batch_op.drop_column('motorcycle_existance_updated_at')

    with op.batch_alter_table('solicitudes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('motorcycle_existance', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('motorcycle_existance_updated_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('solicitudes', schema=None) as batch_op:
        batch_op.drop_column('motorcycle_existance_updated_at')
        batch_op.drop_column('motorcycle_existance')

    with op.batch_alter_table('motorcycles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('motorcycle_existance_updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('motorcycle_existance', sa.VARCHAR(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
