"""empty message

Revision ID: c9adf3129360
Revises: 30ba280d5792
Create Date: 2025-04-04 15:58:48.722721

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "c9adf3129360"
down_revision = "30ba280d5792"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("banks_offers", schema=None) as batch_op:
        pass
        # batch_op.add_column(sa.Column('max_loan_term_months', sa.Integer(), nullable=False))
        # batch_op.drop_column('max_dowmax_loan_term_monthsnpayment')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("banks_offers", schema=None) as batch_op:
        pass
        # batch_op.add_column(sa.Column('max_dowmax_loan_term_monthsnpayment', sa.INTEGER(), autoincrement=False, nullable=False))
        # batch_op.drop_column('max_loan_term_months')

    # ### end Alembic commands ###
