"""Set BankOfferRequirement

Revision ID: ca88ebe1db16
Revises: 24a0d7da2423
Create Date: 2025-09-02 13:52:02.023569

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca88ebe1db16'
down_revision = '24a0d7da2423'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Create enum types first
    requirementtype_enum = sa.Enum('FIELD', 'DOCUMENT', name='requirementtype')
    requirementtype_enum.create(op.get_bind())
    
    requirementstatus_enum = sa.Enum('REQUIRED', 'SUGGESTED', name='requirementstatus')
    requirementstatus_enum.create(op.get_bind())
    
    with op.batch_alter_table('banks_offers_requirements', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type_requirement', sa.Enum('FIELD', 'DOCUMENT', name='requirementtype'), nullable=False))
        batch_op.add_column(sa.Column('requirement_key', sa.String(length=255), nullable=False))
        batch_op.alter_column('requirement_status',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('REQUIRED', 'SUGGESTED', name='requirementstatus'),
               existing_nullable=False,
               postgresql_using='requirement_status::requirementstatus')
        batch_op.drop_column('field_reference')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('banks_offers_requirements', schema=None) as batch_op:
        batch_op.add_column(sa.Column('field_reference', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
        batch_op.alter_column('requirement_status',
               existing_type=sa.Enum('REQUIRED', 'SUGGESTED', name='requirementstatus'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
        batch_op.drop_column('requirement_key')
        batch_op.drop_column('type_requirement')

    # Drop enum types
    sa.Enum(name='requirementtype').drop(op.get_bind())
    sa.Enum(name='requirementstatus').drop(op.get_bind())

    # ### end Alembic commands ###
