"""Add cascade delete to relation between conversation and messages

Revision ID: cac8d7d79f11
Revises: 7451da5f42f6
Create Date: 2025-07-18 00:31:07.395969

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cac8d7d79f11'
down_revision = '7451da5f42f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_constraint('messages_conversation_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'conversations', ['conversation_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('messages_conversation_id_fkey', 'conversations', ['conversation_id'], ['id'])

    # ### end Alembic commands ###
