"""empty message

Revision ID: d28cb59ac267
Revises: 569ac5a8bbde
Create Date: 2025-08-12 15:27:18.948394

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd28cb59ac267'
down_revision = '569ac5a8bbde'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.create_index('idx_conversation_direction_timestamp', ['conversation_id', 'direction', 'timestamp'], unique=False)
        batch_op.create_index('idx_conversation_timestamp', ['conversation_id', 'timestamp'], unique=False)
        batch_op.create_index('idx_media_messages', ['media_id'], unique=False, postgresql_where=sa.text('media_id IS NOT NULL'))
        batch_op.create_index('idx_message_type_timestamp', ['message_type', 'timestamp'], unique=False)
        batch_op.create_index('idx_reply_messages', ['reply_to_message_id'], unique=False, postgresql_where=sa.text('reply_to_message_id IS NOT NULL'))
        batch_op.create_index('idx_status_timestamp', ['status', 'timestamp'], unique=False)
        batch_op.create_index('idx_user_timestamp', ['user_id', 'timestamp'], unique=False)
        batch_op.create_index('idx_wa_message_conversation', ['wa_message_id', 'conversation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_messages_conversation_id'), ['conversation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_messages_direction'), ['direction'], unique=False)
        batch_op.create_index(batch_op.f('ix_messages_media_id'), ['media_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_messages_message_type'), ['message_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_messages_reply_to_message_id'), ['reply_to_message_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_messages_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_messages_status_updated_at'), ['status_updated_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_messages_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_messages_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_messages_wa_message_id'), ['wa_message_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_messages_wa_message_id'))
        batch_op.drop_index(batch_op.f('ix_messages_user_id'))
        batch_op.drop_index(batch_op.f('ix_messages_timestamp'))
        batch_op.drop_index(batch_op.f('ix_messages_status_updated_at'))
        batch_op.drop_index(batch_op.f('ix_messages_status'))
        batch_op.drop_index(batch_op.f('ix_messages_reply_to_message_id'))
        batch_op.drop_index(batch_op.f('ix_messages_message_type'))
        batch_op.drop_index(batch_op.f('ix_messages_media_id'))
        batch_op.drop_index(batch_op.f('ix_messages_direction'))
        batch_op.drop_index(batch_op.f('ix_messages_conversation_id'))
        batch_op.drop_index('idx_wa_message_conversation')
        batch_op.drop_index('idx_user_timestamp')
        batch_op.drop_index('idx_status_timestamp')
        batch_op.drop_index('idx_reply_messages', postgresql_where=sa.text('reply_to_message_id IS NOT NULL'))
        batch_op.drop_index('idx_message_type_timestamp')
        batch_op.drop_index('idx_media_messages', postgresql_where=sa.text('media_id IS NOT NULL'))
        batch_op.drop_index('idx_conversation_timestamp')
        batch_op.drop_index('idx_conversation_direction_timestamp')

    # ### end Alembic commands ###
