"""Add bank offer requirements table for dynamic field validation

Revision ID: d8f9c03b0650
Revises: c7f8b92a9549
Create Date: 2025-09-01 19:30:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd8f9c03b0650'
down_revision = 'c7f8b92a9549'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('banks_offers_requirements',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('bank_id', sa.Integer(), nullable=False),
        sa.Column('field_reference', sa.String(length=255), nullable=False),
        sa.Column('requirement_status', sa.String(length=50), nullable=False),
        sa.Column('validation_rule', sa.String(length=255), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(['bank_id'], ['bancos.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    
    # Create index on bank_id for better performance
    op.create_index(op.f('ix_banks_offers_requirements_bank_id'), 'banks_offers_requirements', ['bank_id'], unique=False)
    
    # Create index on field_reference for better search performance
    op.create_index(op.f('ix_banks_offers_requirements_field_reference'), 'banks_offers_requirements', ['field_reference'], unique=False)
    
    # Create index on requirement_status for filtering
    op.create_index(op.f('ix_banks_offers_requirements_requirement_status'), 'banks_offers_requirements', ['requirement_status'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_banks_offers_requirements_requirement_status'), table_name='banks_offers_requirements')
    op.drop_index(op.f('ix_banks_offers_requirements_field_reference'), table_name='banks_offers_requirements')
    op.drop_index(op.f('ix_banks_offers_requirements_bank_id'), table_name='banks_offers_requirements')
    op.drop_table('banks_offers_requirements')
    # ### end Alembic commands ###
