"""Add new models for manage the income proof documents

Revision ID: dc6f0e9c4661
Revises: 9db8f13f09c9
Create Date: 2025-06-30 15:43:24.605350

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc6f0e9c4661'
down_revision = '9db8f13f09c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('income_proof_documents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('document_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=True),
    sa.Column('month', sa.String(length=20), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clientes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('file_statuses', schema=None) as batch_op:
        batch_op.drop_column('incomeProof_three')
        batch_op.drop_column('incomeProof_two')
        batch_op.drop_column('incomeProof')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('file_statuses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('incomeProof', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('incomeProof_two', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('incomeProof_three', sa.VARCHAR(length=50), autoincrement=False, nullable=True))

    op.drop_table('income_proof_documents')
    # ### end Alembic commands ###
