"""LA-364 - Set models for identify process and give to the user the steps by funnel selected

Revision ID: df95366379a4
Revises: 74be7c8ad79a
Create Date: 2025-09-05 18:04:18.109752

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df95366379a4'
down_revision = '74be7c8ad79a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('process_types',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('payment_method', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('process_steps',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('process_type_id', sa.Integer(), nullable=False),
    sa.Column('step_order', sa.Integer(), nullable=False),
    sa.Column('step_name', sa.String(length=200), nullable=False),
    sa.ForeignKeyConstraint(['process_type_id'], ['process_types.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('solicitud_status_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('process_type_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'process_types', ['process_type_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('solicitud_status_history', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('process_type_id')

    op.drop_table('process_steps')
    op.drop_table('process_types')
    # ### end Alembic commands ###
