"""add sync crm columns for client and solicitud

Revision ID: e798088f78fc
Revises: c30e90a83b98
Create Date: 2025-01-31 12:07:30.508918

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e798088f78fc'
down_revision = 'c30e90a83b98'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('crm_sync_id', sa.String(), nullable=True))

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_constraint('payments_purchase_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'purchases', ['purchase_id'], ['id'])

    with op.batch_alter_table('solicitudes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('crm_sync_id', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('solicitudes', schema=None) as batch_op:
        batch_op.drop_column('crm_sync_id')

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('payments_purchase_id_fkey', 'purchases', ['purchase_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')

    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.drop_column('crm_sync_id')

    # ### end Alembic commands ###
