"""empty message

Revision ID: f193e17c3123
Revises: c9adf3129360
Create Date: 2025-04-04 22:21:09.349512

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f193e17c3123'
down_revision = 'c9adf3129360'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bank_offers_brands',
    sa.Column('bank_offer_id', sa.Integer(), nullable=False),
    sa.Column('brand_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['bank_offer_id'], ['banks_offers.id'], ),
    sa.ForeignKeyConstraint(['brand_id'], ['motorcycle_brands.id'], ),
    sa.PrimaryKeyConstraint('bank_offer_id', 'brand_id')
    )
    with op.batch_alter_table('banks_offers', schema=None) as batch_op:
        batch_op.drop_constraint('banks_offers_brand_id_fkey', type_='foreignkey')
        batch_op.drop_column('brand_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('banks_offers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('brand_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('banks_offers_brand_id_fkey', 'motorcycle_brands', ['brand_id'], ['id'])

    op.drop_table('bank_offers_brands')
    # ### end Alembic commands ###
