"""New columns in bank offers table

Revision ID: f37da03d1d05
Revises: 177da8cb810e
Create Date: 2025-09-22 14:20:07.175759

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f37da03d1d05'
down_revision = '177da8cb810e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Create the enum type first
    financerestrictiontype_enum = sa.Enum('AMOUNT_TO_FINANCE', 'INVOICE_VALUE', 'AMOUNT_AND_INVOICE', name='financerestrictiontype')
    financerestrictiontype_enum.create(op.get_bind())
    
    with op.batch_alter_table('banks_offers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('min_amount_to_finance', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('max_amount_to_finance', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('amount_to_finance_restriction_type', financerestrictiontype_enum, nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('banks_offers', schema=None) as batch_op:
        batch_op.drop_column('amount_to_finance_restriction_type')
        batch_op.drop_column('max_amount_to_finance')
        batch_op.drop_column('min_amount_to_finance')
    
    # Drop the enum type
    financerestrictiontype_enum = sa.Enum('AMOUNT_TO_FINANCE', 'INVOICE_VALUE', 'AMOUNT_AND_INVOICE', name='financerestrictiontype')
    financerestrictiontype_enum.drop(op.get_bind())

    # ### end Alembic commands ###
