"""LA-251

Revision ID: f857a530d249
Revises: 7e53eb41b7ae
Create Date: 2025-05-13 09:20:14.080052

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "f857a530d249"
down_revision = "7e53eb41b7ae"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("solicitud_banks", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("created_at", sa.DateTime(timezone=True), nullable=False)
        )

    with op.batch_alter_table("solicitudes", schema=None) as batch_op:
        batch_op.drop_constraint(
            "solicitudes_bank_id_applicated_fkey", type_="foreignkey"
        )
        batch_op.drop_column("bank_id_applicated")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("solicitudes", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "bank_id_applicated", sa.INTEGER(), autoincrement=False, nullable=True
            )
        )
        batch_op.create_foreign_key(
            "solicitudes_bank_id_applicated_fkey",
            "bancos",
            ["bank_id_applicated"],
            ["id"],
        )

    with op.batch_alter_table("solicitud_banks", schema=None) as batch_op:
        batch_op.drop_column("created_at")

    # ### end Alembic commands ###
