"""LA-362 - Set purchase_fee_with_vat and financing_fee_with_vat columns

Revision ID: fcfe1bd43cd6
Revises: fda4eeea86ea
Create Date: 2025-08-18 15:51:21.855699

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fcfe1bd43cd6'
down_revision = 'fda4eeea86ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        # batch_op.add_column(sa.Column('purchase_fee_with_vat', sa.Float(), nullable=True))
        # batch_op.add_column(sa.Column('financing_fee_with_vat', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('purchase_fee_vat', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('financing_fee_vat', sa.Float(), nullable=True))
        # batch_op.drop_column('mercado_pago_fee')
        # batch_op.drop_column('financing_fee')

    # with op.batch_alter_table('sucursales', schema=None) as batch_op:
    #     batch_op.alter_column('active',
    #            existing_type=sa.BOOLEAN(),
    #            nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sucursales', schema=None) as batch_op:
        batch_op.alter_column('active',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('financing_fee', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('mercado_pago_fee', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.drop_column('financing_fee_vat')
        batch_op.drop_column('purchase_fee_vat')
        batch_op.drop_column('financing_fee_with_vat')
        batch_op.drop_column('purchase_fee_with_vat')

    # ### end Alembic commands ###
