"""Set active column for sucursales model

Revision ID: fda4eeea86ea
Revises: 7e26ac48b37f
Create Date: 2025-08-15 09:42:49.082351

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "fda4eeea86ea"
down_revision = "7e26ac48b37f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("sucursales", schema=None) as batch_op:
        batch_op.add_column(sa.Column("active", sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("sucursales", schema=None) as batch_op:
        batch_op.drop_column("active")

    # ### end Alembic commands ###
